kadai_002_2/NAGOYAEMESHI/nagoyameshi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
]

kadai_002_2/NAGOYAEMESHI/userapp/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from .views import (
    IndexView, SignUpView, Login, Search,
    SubscriptionView, MyPageView, ProfileView,
    ReservationsView, FavoritesView, PaymentMethodView, CancelSubscriptionView,
    ShopInfoView, ProfileEditView, ReservationCancelView,
    unfavorite_shop, SubscribeView, ReviewDeleteView, ReviewEditView, success, cancel, SubscriptionPaymentView
)

app_name = 'userapp'

urlpatterns = [
    # ホームページ
    path('', IndexView.as_view(), name='index'),

    # ユーザー登録ページ
    path('signup/', SignUpView.as_view(), name='signup'),

    # ログインページ
    path('login/', Login.as_view(), name='login'),

    # ログアウト
    path('logout/', LogoutView.as_view(), name='logout'),

    # 検索機能
    path('search/', Search, name='search'),

    # 店舗情報ページ
    path('shop_info/<int:shop_id>/', ShopInfoView.as_view(), name='shop_info'),

    # サブスクリプション情報ページ
    path('subscription/', SubscriptionView.as_view(), name='subscription'),

    # マイページ
    path('mypage/', MyPageView.as_view(), name='mypage'),

    # プロフィールページ
    path('mypage/profile/', ProfileView.as_view(), name='profile'),

    # プロフィール編集ページ
    path('mypage/profile/edit/', ProfileEditView.as_view(), name='profile_edit'),

    # ユーザーの予約一覧
    path('mypage/reservations/', ReservationsView.as_view(), name='reservations'),

    # 予約キャンセルページ
    path('mypage/reservations/cancel/<int:pk>/', ReservationCancelView.as_view(), name='reservation_cancel'),

    # ユーザーのお気に入り一覧
    path('mypage/favorites/', FavoritesView.as_view(), name='favorites'),

    # お気に入りからの削除
    path('mypage/favorites/unfavorite/<int:shop_id>/', unfavorite_shop, name='unfavorite_shop'),

    # 支払い方法ページ
    path('mypage/payment_method/', PaymentMethodView.as_view(), name='payment_method'),

    # サブスクリプションキャンセルページ
    path('mypage/cancel_subscription/', CancelSubscriptionView.as_view(), name='cancel_subscription'),

    # サブスクリプション登録用のURLパターン
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),

    # レビュー削除
    path('review/delete/<int:pk>/', ReviewDeleteView.as_view(), name='review_delete'),

    # レビュー編集
    path('review/edit/<int:pk>/', ReviewEditView.as_view(), name='review_edit'),

    # 支払いに成功した後の画面
    path('subscription/success/', success, name='subscription_success'),

    # 支払いに失敗した後の画面
    path('subscription/cancel/', cancel, name='subscription_cancel'),

    # 支払い方法登録
    path('subscription/payment/', SubscriptionPaymentView.as_view(), name='subscription_payment'),

    # パスワードリセット関連のURLパターン
    path('password_reset/', PasswordResetView.as_view(template_name='userapp/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='userapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='userapp/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='userapp/password_reset_complete.html'), name='password_reset_complete'),
]

kadai_002_2/NAGOYAEMESHI/userapp/forms.py
from django import forms
from .models import Category, Review, Reservation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()

SCORE_CHOICES = [
    (1, '★'),
    (2, '★★'),
    (3, '★★★'),
    (4, '★★★★'),
    (5, '★★★★★'),
]

class SearchForm(forms.Form):
    selected_category = forms.ModelChoiceField(
        label='業態',
        required=False,
        queryset=Category.objects.all(),
    )
    freeword = forms.CharField(min_length=2, max_length=100, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        selected_category = self.fields['selected_category']

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class EmailLoginForm(AuthenticationForm):
    username = forms.EmailField(label='Email', max_length=254)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['score', 'comment']

# サブスクリプション登録
class SubscriptionForm(forms.Form):
    stripe_token = forms.CharField()

# 予約フォーム
class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['date_time', 'num_people', 'shop']  # datetimeと人数を追加
        widgets = {
            'date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

# レビュー編集フォーム
class ReviewEditForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['score', 'comment']
        widgets = {
            'score': forms.RadioSelect(choices=SCORE_CHOICES),
            'comment': forms.Textarea(attrs={'rows': 4}),
        }

# プロフィール編集フォーム
class ProfileEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'username', 'email', 'postal_code', 'address', 
            'phone_number', 'birthday', 'job'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

kadai_002_2/NAGOYAEMESHI/userapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, TemplateView, View, FormView, ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from .models import Review, Category, Subscription, Shop, Reservation, Favorite
from .forms import SearchForm, SignUpForm, EmailLoginForm, ReviewForm, ReservationForm, ReviewEditForm, SubscriptionForm, ProfileEditForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Avg
from django.contrib import messages
from django.conf import settings
import stripe
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from .mixins import PaidMemberRequiredMixin
import json

stripe.api_key = settings.STRIPE_SECRET_KEY

# 店舗情報の表示および操作を行うビュー
class ShopInfoView(View):
    template_name = 'userapp/shop_info.html'

    def get(self, request, shop_id):
        return self.render_shop_info(request, shop_id)

    def post(self, request, shop_id):
        shop = get_object_or_404(Shop, pk=shop_id)
        if not request.user.is_authenticated:
            messages.error(request, 'この操作を行うにはログインが必要です。', extra_tags='login')
            return redirect('userapp:login')

        try:
            subscription = Subscription.objects.get(user=request.user)
            if not subscription.active:
                raise Subscription.DoesNotExist
        except Subscription.DoesNotExist:
            return redirect('userapp:subscription')

        # 各フォームの処理
        if 'review_submit' in request.POST:
            review_form = ReviewForm(data=request.POST)
            if review_form.is_valid():
                existing_review = Review.objects.filter(shop=shop, user=request.user).first()
                if existing_review:
                    messages.error(request, '既にこの店舗にレビューを投稿しています。', extra_tags='review')
                else:
                    review = Review()
                    review.shop = shop
                    review.user = request.user
                    review.score = review_form.cleaned_data['score']
                    review.comment = review_form.cleaned_data['comment']
                    review.save()
                    messages.success(request, 'レビューの投稿が完了しました。', extra_tags='review')
            else:
                messages.error(request, 'レビューの投稿にエラーがあります。', extra_tags='review')
            return redirect('userapp:shop_info', shop_id=shop_id)
        elif 'reservation_submit' in request.POST:
            reservation_form = ReservationForm(data=request.POST)
            if reservation_form.is_valid():
                reservation = reservation_form.save(commit=False)
                reservation.user = request.user
                reservation.shop = shop
                reservation.save()
                messages.success(request, '予約が完了しました。', extra_tags='reservation')
            else:
                messages.error(request, '予約の投稿にエラーがあります。', extra_tags='reservation')
            return redirect('userapp:shop_info', shop_id=shop_id)
        elif 'favorite_submit' in request.POST:
            Favorite.objects.create(shop=shop, user=request.user)
            messages.success(request, 'お気に入りに追加しました。', extra_tags='favorite')
            return redirect('userapp:shop_info', shop_id=shop_id)
        elif 'unfavorite_submit' in request.POST:
            Favorite.objects.filter(shop=shop, user=request.user).delete()
            messages.success(request, 'お気に入りから削除しました。', extra_tags='favorite')
            return redirect('userapp:shop_info', shop_id=shop_id)

        return redirect('userapp:shop_info', shop_id=shop_id)

    def render_shop_info(self, request, shop_id):
        shop = get_object_or_404(Shop, pk=shop_id)
        review_count = Review.objects.filter(shop=shop).count()
        score_ave = Review.objects.filter(shop=shop).aggregate(Avg('score'))
        average = score_ave['score__avg']
        average_rate = average / 5 * 100 if average else 0
        review_form = ReviewForm()
        review_list = Review.objects.filter(shop=shop)
        reservation_form = ReservationForm(initial={'shop': shop})

        is_favorite = False
        if request.user.is_authenticated:
            is_favorite = Favorite.objects.filter(shop=shop, user=request.user).exists()

        params = {
            'title': '店舗詳細',
            'review_count': review_count,
            'shop': shop,
            'review_form': review_form,
            'review_list': review_list,
            'average': average,
            'average_rate': average_rate,
            'reservation_form': reservation_form,
            'is_favorite': is_favorite
        }
        return render(request, self.template_name, params)

# ホームページの表示
class IndexView(TemplateView):
    template_name = 'userapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        searchform = SearchForm()
        pickup_list = Shop.objects.all()[:10]
        review_list = Review.objects.select_related('shop').all()[:10]
        category_list = Category.objects.all()

        context.update({
            'searchform': searchform,
            'pickup_list': pickup_list,
            'review_list': review_list,
            'category_list': category_list
        })

        return context

# 検索機能のビュー
def Search(request):
    total_hit_count = 0
    shop_info = []

    if request.method == 'GET':
        searchform = SearchForm(request.GET)

        if searchform.is_valid():
            category_id = request.GET.get('selected_category', '')
            freeword = request.GET.get('freeword', '')

            query = Shop.objects.all()

            if category_id:
                query = query.filter(category_id=category_id)
            
            if freeword:
                query = query.filter(name__icontains=freeword)

            total_hit_count = query.count()
            shop_info = query[:10]

    params = {
        'total_hit_count': total_hit_count,
        'shop_info': shop_info,
        'searchform': searchform,
    }

    return render(request, 'userapp/search.html', params)

# 予約キャンセルのビュー
class ReservationCancelView(LoginRequiredMixin, DeleteView):
    model = Reservation
    template_name = 'userapp/reservation_confirm_cancel.html'
    success_url = reverse_lazy('userapp:subscription')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(self.request, '予約をキャンセルしました。', extra_tags='reservation')
        return redirect(success_url)

# レビュー編集のビュー
class ReviewEditView(LoginRequiredMixin, PaidMemberRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewEditForm
    template_name = 'userapp/review_form.html'

    def get_success_url(self):
        messages.success(self.request, 'レビューを更新しました。', extra_tags='review')
        return reverse('userapp:subscription')

# レビュー削除のビュー
class ReviewDeleteView(LoginRequiredMixin, PaidMemberRequiredMixin, DeleteView):
    model = Review
    template_name = 'userapp/review_confirm_delete.html'

    def get_success_url(self):
        messages.success(self.request, 'レビューを削除しました。', extra_tags='review')
        return reverse('userapp:subscription')

# 新規ユーザー登録のビュー
class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'userapp/signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save()
            # Stripe Checkout Sessionを作成
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                customer_email=user.email,
                line_items=[
                    {
                        'price': settings.STRIPE_PRICE_ID,
                        'quantity': 1,
                    },
                ],
                mode='subscription',
                success_url=request.build_absolute_uri('/success/'),
                cancel_url=request.build_absolute_uri('/cancel/'),
            )
            # 一時的にユーザー情報を保存
            Subscription.objects.create(
                user=user,
                stripe_customer_id='',
                stripe_subscription_id='',
                active=False,
            )
            return redirect(checkout_session.url)
        return render(request, 'userapp/signup.html', {'form': form})

# ログインのビュー
class Login(LoginView):
    form_class = EmailLoginForm
    template_name = 'userapp/login.html'

# サブスクリプション情報の表示ビュー
@method_decorator(login_required, name='dispatch')
class SubscriptionView(TemplateView):
    template_name = 'userapp/subscription.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        try:
            subscription = Subscription.objects.get(user=self.request.user)
            context['subscription'] = subscription
        except Subscription.DoesNotExist:
            context['subscription'] = None
            messages.error(self.request, 'この機能を使用するには有料会員登録が必要です')
        
        # 公開鍵（テスト用）
        context["sk_test_51PegsNHgh7sLH8myPovEAkC4vKrXmAMecdKrBbaW7tS4tKWH0ATCpAjz0HS5Qdbc5lnH1Zu5WHI4quuQCYTsx4fF0033T7zJoP"] = settings.STRIPE_PUBLISHABLE_KEY
        
        return context

# プロフィール編集のビュー

kadai_002_2/NAGOYAEMESHI/userapp/templates/base.html
{% load static %}

<!doctype html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="{% static 'js/index.js' %}"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/common.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
    <div id="fb-root"></div>
    <title>NAGOYAMESI</title>
    <script async defer crossorigin="anonymous" src="https://connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v3.3&appId=800322963696452"></script>
    <script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>
    {% block css %}{% endblock css %}
</head>
    
<body>    
    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{% url 'userapp:index' %}">NAGOYAMESI</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'userapp:index' %}">TOP<span class="sr-only">(current)</span></a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-item nav-link" href="{% url 'userapp:mypage' %}">マイページ</a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'userapp:profile' %}">会員情報</a>
                        <a class="dropdown-item" href="{% url 'userapp:reservations' %}">予約一覧</a>
                        <a class="dropdown-item" href="{% url 'userapp:favorites' %}">お気に入り一覧</a>
                        <a class="dropdown-item" href="{% url 'userapp:payment_method' %}">お支払い方法</a>
                        <a class="dropdown-item" href="{% url 'userapp:cancel_subscription' %}">有料プラン解約</a>
                    </div>
                </li>
                <li class="nav-item">
                    <form method="post" action="{% url 'userapp:logout' %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-link nav-link">ログアウト</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userapp:login' %}">ログイン</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'userapp:signup' %}">新規ユーザ登録</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <br>
    {% block content %}
    {% endblock %}
    <br><br>
    <div class="container">
        <div class="row">
            <div class="col-md-12 text-center">
                <br/><br/>
                <hr/>
                <p>NAGOYAMESHI</p>
                <br/><br/>  
            </div>
        </div>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6jHty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>