kadai_002_2/NAGOYAEMESHI/nagoyameshi/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('userapp.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
]

kadai_002_2/NAGOYAEMESHI/userapp/urls.py
from django.urls import path
from django.contrib.auth.views import (
    LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
)
from .views import (
    IndexView, SignUpView, Login, Search,
    SubscriptionView, MyPageView, ProfileView,
    ReservationsView, FavoritesView, PaymentMethodView, CancelSubscriptionView,
    ShopInfoView, ProfileEditView, ReservationCancelView,
    unfavorite_shop, SubscribeView, ReviewDeleteView, ReviewEditView, success, cancel, SubscriptionPaymentView
)

app_name = 'userapp'

urlpatterns = [
    # ホームページ
    path('', IndexView.as_view(), name='index'),

    # ユーザー登録ページ
    path('signup/', SignUpView.as_view(), name='signup'),

    # ログインページ
    path('login/', Login.as_view(), name='login'),

    # ログアウト
    path('logout/', LogoutView.as_view(), name='logout'),

    # 検索機能
    path('search/', Search, name='search'),

    # 店舗情報ページ
    path('shop_info/<int:shop_id>/', ShopInfoView.as_view(), name='shop_info'),

    # サブスクリプション情報ページ
    path('subscription/', SubscriptionView.as_view(), name='subscription'),

    # マイページ
    path('mypage/', MyPageView.as_view(), name='mypage'),

    # プロフィールページ
    path('mypage/profile/', ProfileView.as_view(), name='profile'),

    # プロフィール編集ページ
    path('mypage/profile/edit/', ProfileEditView.as_view(), name='profile_edit'),

    # ユーザーの予約一覧
    path('mypage/reservations/', ReservationsView.as_view(), name='reservations'),

    # 予約キャンセルページ
    path('mypage/reservations/cancel/<int:pk>/', ReservationCancelView.as_view(), name='reservation_cancel'),

    # ユーザーのお気に入り一覧
    path('mypage/favorites/', FavoritesView.as_view(), name='favorites'),

    # お気に入りからの削除
    path('mypage/favorites/unfavorite/<int:shop_id>/', unfavorite_shop, name='unfavorite_shop'),

    # 支払い方法ページ
    path('mypage/payment_method/', PaymentMethodView.as_view(), name='payment_method'),

    # サブスクリプションキャンセルページ
    path('mypage/cancel_subscription/', CancelSubscriptionView.as_view(), name='cancel_subscription'),

    # サブスクリプション登録用のURLパターン
    path('subscribe/', SubscribeView.as_view(), name='subscribe'),

    # レビュー削除
    path('review/delete/<int:pk>/', ReviewDeleteView.as_view(), name='review_delete'),

    # レビュー編集
    path('review/edit/<int:pk>/', ReviewEditView.as_view(), name='review_edit'),

    # 支払いに成功した後の画面
    path('subscription/success/', success, name='subscription_success'),

    # 支払いに失敗した後の画面
    path('subscription/cancel/', cancel, name='subscription_cancel'),

    # 支払い方法登録
    path('subscription/payment/', SubscriptionPaymentView.as_view(), name='subscription_payment'),

    # パスワードリセット関連のURLパターン
    path('password_reset/', PasswordResetView.as_view(template_name='userapp/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='userapp/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(template_name='userapp/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name='userapp/password_reset_complete.html'), name='password_reset_complete'),
]

kadai_002_2/NAGOYAEMESHI/userapp/forms.py
from django import forms
from .models import Category, Review, Reservation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UserChangeForm
from django.conf import settings
from django.contrib.auth import get_user_model

User = get_user_model()

SCORE_CHOICES = [
    (1, '★'),
    (2, '★★'),
    (3, '★★★'),
    (4, '★★★★'),
    (5, '★★★★★'),
]

class SearchForm(forms.Form):
    selected_category = forms.ModelChoiceField(
        label='業態',
        required=False,
        queryset=Category.objects.all(),
    )
    freeword = forms.CharField(min_length=2, max_length=100, label='', required=False)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        selected_category = self.fields['selected_category']

class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class EmailLoginForm(AuthenticationForm):
    username = forms.EmailField(label='Email', max_length=254)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['score', 'comment']

# サブスクリプション登録
class SubscriptionForm(forms.Form):
    stripe_token = forms.CharField()

# 予約フォーム
class ReservationForm(forms.ModelForm):
    class Meta:
        model = Reservation
        fields = ['date_time', 'num_people', 'shop']  # datetimeと人数を追加
        widgets = {
            'date_time': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }

# レビュー編集フォーム
class ReviewEditForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['score', 'comment']
        widgets = {
            'score': forms.RadioSelect(choices=SCORE_CHOICES),
            'comment': forms.Textarea(attrs={'rows': 4}),
        }

# プロフィール編集フォーム
class ProfileEditForm(UserChangeForm):
    class Meta:
        model = User
        fields = [
            'username', 'email', 'postal_code', 'address', 
            'phone_number', 'birthday', 'job'
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'
            field.widget.attrs['placeholder'] = field.label

kadai_002_2/NAGOYAEMESHI/userapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import CreateView, TemplateView, View, FormView, ListView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import get_user_model
from .models import Review, Category, Subscription, Shop, Reservation, Favorite
from .forms import SearchForm, SignUpForm, EmailLoginForm, ReviewForm, ReservationForm, ReviewEditForm, SubscriptionForm, ProfileEditForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.views import LoginView, LogoutView
from django.db.models import Avg
from django.contrib import messages
from django.conf import settings
import stripe
from django.http import JsonResponse, HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.urls import reverse, reverse_lazy
from .mixins import PaidMemberRequiredMixin
import json

stripe.api_key = settings.STRIPE_SECRET_KEY

# 店舗情報の表示および操作を行うビュー
class ShopInfoView(View):
    template_name = 'userapp/shop_info.html'

    def get(self, request, shop_id):
        return self.render_shop_info(request, shop_id)

    def post(self, request, shop_id):
        shop = get_object_or_404(Shop, pk=shop_id)
        if not request.user.is_authenticated:
            messages.error(request, 'この操作を行うにはログインが必要です。', extra_tags='login')
            return redirect('userapp:login')

        try:
            subscription = Subscription.objects.get(user=request.user)
            if not subscription.active:
                raise Subscription.DoesNotExist
        except Subscription.DoesNotExist:
            return redirect('userapp:subscription')

        # 各フォームの処理
        if 'review_submit' in request.POST:
            review_form = ReviewForm(data=request.POST)
            if review_form.is_valid():
                existing_review = Review.objects.filter(shop=shop, user=request.user).first()
                if existing_review:
                    messages.error(request, '既にこの店舗にレビューを投稿しています。', extra_tags='review')
                else:
                    review = Review()
                    review.shop = shop
                    review.user = request.user
                    review.score = review_form.cleaned_data['score']
                    review.comment = review_form.cleaned_data['comment']
                    review.save()
                    messages.success(request, 'レビューの投稿が完了しました。', extra_tags='review')
            else:
                messages.error(request, 'レビューの投稿にエラーがあります。', extra_tags='review')
            return redirect('userapp:shop_info', shop_id=shop_id)
        elif 'reservation_submit' in request.POST:
            reservation_form = ReservationForm(data=request.POST)
            if reservation_form.is_valid():
                reservation = reservation_form.save(commit=False)
                reservation.user = request.user
                reservation.shop = shop
                reservation.save()
                messages.success(request, '予約が完了しました。', extra_tags='reservation')
            else:
                messages.error(request, '予約の投稿にエラーがあります。', extra_tags='reservation')
            return redirect('userapp:shop_info', shop_id=shop_id)
        elif 'favorite_submit' in request.POST:
            Favorite.objects.create(shop=shop, user=request.user)
            messages.success(request, 'お気に入りに追加しました。', extra_tags='favorite')
            return redirect('userapp:shop_info', shop_id=shop_id)
        elif 'unfavorite_submit' in request.POST:
            Favorite.objects.filter(shop=shop, user=request.user).delete()
            messages.success(request, 'お気に入りから削除しました。', extra_tags='favorite')
            return redirect('userapp:shop_info', shop_id=shop_id)

        return redirect('userapp:shop_info', shop_id=shop_id)

    def render_shop_info(self, request, shop_id):
        shop = get_object_or_404(Shop, pk=shop_id)
        review_count = Review.objects.filter(shop=shop).count()
        score_ave = Review.objects.filter(shop=shop).aggregate(Avg('score'))
        average = score_ave['score__avg']
        average_rate = average / 5 * 100 if average else 0
        review_form = ReviewForm()
        review_list = Review.objects.filter(shop=shop)
        reservation_form = ReservationForm(initial={'shop': shop})

        is_favorite = False
        if request.user.is_authenticated:
            is_favorite = Favorite.objects.filter(shop=shop, user=request.user).exists()

        params = {
            'title': '店舗詳細',
            'review_count': review_count,
            'shop': shop,
            'review_form': review_form,
            'review_list': review_list,
            'average': average,
            'average_rate': average_rate,
            'reservation_form': reservation_form,
            'is_favorite': is_favorite
        }
        return render(request, self.template_name, params)

# ホームページの表示
class IndexView(TemplateView):
    template_name = 'userapp/index.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        searchform = SearchForm()
        pickup_list = Shop.objects.all()[:10]
        review_list = Review.objects.select_related('shop').all()[:10]
        category_list = Category.objects.all()

        context.update({
            'searchform': searchform,
            'pickup_list': pickup_list,
            'review_list': review_list,
            'category_list': category_list
        })

        return context

# 検索機能のビュー
def Search(request):
    total_hit_count = 0
    shop_info = []

    if request.method == 'GET':
        searchform = SearchForm(request.GET)

        if searchform.is_valid():
            category_id = request.GET.get('selected_category', '')
            freeword = request.GET.get('freeword', '')

            query = Shop.objects.all()

            if category_id:
                query = query.filter(category_id=category_id)
            
            if freeword:
                query = query.filter(name__icontains=freeword)

            total_hit_count = query.count()
            shop_info = query[:10]

    params = {
        'total_hit_count': total_hit_count,
        'shop_info': shop_info,
        'searchform': searchform,
    }

    return render(request, 'userapp/search.html', params)

# 予約キャンセルのビュー
class ReservationCancelView(LoginRequiredMixin, DeleteView):
    model = Reservation
    template_name = 'userapp/reservation_confirm_cancel.html'
    success_url = reverse_lazy('userapp:subscription')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        success_url = self.get_success_url()
        self.object.delete()
        messages.success(self.request, '予約をキャンセルしました。', extra_tags='reservation')
        return redirect(success_url)

# レビュー編集のビュー
class ReviewEditView(LoginRequiredMixin, PaidMemberRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewEditForm
    template_name = 'userapp/review_form.html'

    def get_success_url(self):
        messages.success(self.request, 'レビューを更新しました。', extra_tags='review')
        return reverse('userapp:subscription')

# レビュー削除のビュー
class ReviewDeleteView(LoginRequiredMixin, PaidMemberRequiredMixin, DeleteView):
    model = Review
    template_name = 'userapp/review_confirm_delete.html'

    def get_success_url(self):
        messages.success(self.request, 'レビューを削除しました。', extra_tags='review')
        return reverse('userapp:subscription')

# 新規ユーザー登録のビュー
class SignUp(CreateView):
    form_class = SignUpForm
    template_name = 'userapp/signup.html'

    def post(self, request, *args, **kwargs):
        form = self.form_class(data=request.POST)
        if form.is_valid():
            user = form.save()
            # Stripe Checkout Sessionを作成
            checkout_session = stripe.checkout.Session.create(
                payment_method_types=['card'],
                customer_email=user.email,
                line_items=[
                    {
                        'price': settings.STRIPE_PRICE_ID,
                        'quantity': 1,
                    },
                ],
                mode='subscription',
                success_url=request.build_absolute_uri('/success/'),
                cancel_url=request.build_absolute_uri('/cancel/'),
            )
            # 一時的にユーザー情報を保存
            Subscription.objects.create(
                user=user,
                stripe_customer_id='',
                stripe_subscription_id='',
                active=False,
            )
            return redirect(checkout_session.url)
        return render(request, 'userapp/signup.html', {'form': form})

# ログインのビュー
class Login(LoginView):
    form_class = EmailLoginForm
    template_name = 'userapp/login.html'

# サブスクリプション情報の表示ビュー
@method_decorator(login_required, name='dispatch')
class SubscriptionView(TemplateView):
    template_name = 'userapp/subscription.html'

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        try:
            subscription = Subscription.objects.get(user=self.request.user)
            context['subscription'] = subscription
        except Subscription.DoesNotExist:
            context['subscription'] = None
            messages.error(self.request, 'この機能を使用するには有料会員登録が必要です')
        
        # 公開鍵（テスト用）
        context["sk_test_51PegsNHgh7sLH8myPovEAkC4vKrXmAMecdKrBbaW7tS4tKWH0ATCpAjz0HS5Qdbc5lnH1Zu5WHI4quuQCYTsx4fF0033T7zJoP"] = settings.STRIPE_PUBLISHABLE_KEY
        
        return context

# プロフィール編集のビュー

kadai_002_2/NAGOYAEMESHI/userapp/templates/userapp/favorites.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>お気に入り一覧</h1>
    <table class="table">
        <thead>
            <tr>
                <th>店舗名</th>
                <th>郵便番号</th>
                <th>住所</th>
                <th>解除</th>
            </tr>
        </thead>
        <tbody>
            {% for favorite in favorites %}
            <tr>
                <td>{{ favorite.shop.name }}</td>
                <td>{{ favorite.shop.postal_code }}</td>
                <td>{{ favorite.shop.address }}</td>
                <td>
                    <form method="post" action="{% url 'userapp:unfavorite_shop' favorite.shop.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-danger">解除</button>
                    </form>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="4">お気に入りの店舗がありません。</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

kadai_002_2/NAGOYAEMESHI/userapp/templates/userapp/index.html
{% extends "base.html" %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/index.css' %}">
{% endblock css %}

{% block content %}
<section class="search">
    <div id="top_carousel" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="{% static 'image/topimage1.jpg' %}" class="d-block w-100" height="500px" alt="今日はどこで食べようか？">
                <div class="carousel-caption" style="top:50px">
                    <h1><br>名古屋専門の<br>グルメサイト！</h1>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/topimage2.jpg' %}" class="d-block w-100" height="500px">
                <div class="carousel-caption" style="top:50px">
                    <h1><br>名古屋の美味を<br>お届けします</h1>
                </div>
            </div>
            <div class="carousel-item">
                <img src="{% static 'image/topimage3.jpg' %}" class="d-block w-100" height="500px">
                <div class="carousel-caption" style="top:50px">
                    <h1><br>気になるお店の<br>口コミをチェック♪</h1>
                </div>
            </div>
        </div>
        <a class="carousel-control-prev" href="#top_carousel" role="button" data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#top_carousel" role="button" data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>

<form method="GET" action="{% url 'userapp:search' %}" class="form-inline my-2 my-lg-0">
    <select class="form-control mr-sm-2" name="selected_category">
        <option value="">カテゴリ</option>
        {% for category in category_list %}
        <option value="{{ category.id }}">{{ category.name }}</option>
        {% endfor %}
    </select>
    <input class="form-control mr-sm-2" type="text" placeholder="フリーワード" aria-label="Search" name="freeword">
    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">検索</button>
</form>

<div class="container">
    <h2 class="section-title">おすすめ</h2>
</div>
<div class="album py-5 bg-light">
    <div class="container">
        <div class="row">
            {% for item in pickup_list %}
            <div class="col-md-4">    
                <div class="card mb-4 box-shadow">
                    <!-- <img class="card-img-top" src="{{ item.shop_image1 }}" alt="{{ item.name }}"> -->
                    <div class="card-body">
                        <h5 class="card-title">{{ item.name }}</h5>
                        <p class="card-text">{{ item.pr_long }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <a href="{% url 'userapp:shop_info' item.id %}" class="btn common-btn">詳細を見る</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>

<br>
<div class="container">
    <h2 class="section-title">最近のレビュー</h2>
    <div class="row">
        <div class="MultiCarousel" data-items="1,3,5,6" data-slide="1" id="MultiCarousel" data-interval="1000">
            <div class="MultiCarousel-inner">
                {% for item in review_list %}
                <div class="item">
                    <div class="pad15">
                        <img src="{{ item.image_url }}" style="width: 100%;">
                        <p>{{ item.shop.name }}</p>
                        <p>「{{ item.comment }}」</p>
                        {% if item.shop %}
                        <a href="{% url 'userapp:shop_info' item.shop.id %}" class="btn common-btn">詳細を見る</a>
                        {% endif %}
                    </div>
                </div>
                {% endfor %}
            </div>
            <button class="btn btn-primary leftLst"><</button>
            <button class="btn btn-primary rightLst">></button>
        </div>
    </div>
</div>
{% endblock %}

kadai_002_2/NAGOYAEMESHI/userapp/templates/userapp/mypage.html
{% extends "base.html" %}

{% block content %}
<div class="container" style="margin-top:1rem;">

    <ul>
        <li><a href="{% url 'userapp:profile' %}">会員情報</a></li>
        <li><a href="{% url 'userapp:reservations' %}">予約一覧</a></li>
        <li><a href="{% url 'userapp:favorites' %}">お気に入り一覧</a></li>
        {% if subscription and subscription.active %}
            <li><a href="{% url 'userapp:payment_method' %}">お支払い方法</a></li>
            <li><a href="{% url 'userapp:cancel_subscription' %}">有料プラン解約</a></li>
        {% else %}
            <li><a href="{% url 'userapp:payment_method' %}">有料会員へ変更</a></li>
            <li class="text-muted" style="pointer-events: none;">有料プラン解約</li>
        {% endif %}
    </ul>
</div>
<div class="col-md-9">
    {% block mypage_content %}{% endblock %}
</div>
</div>
{% endblock %}

kadai_002_2/NAGOYAEMESHI/userapp/templates/userapp/password_reset.html
{% extends 'base.html' %}
{% block content %}
<h2>パスワードリセット</h2>
<p>パスワードリセットのリンクを含むメールを送信します。登録されたメールアドレスを入力してください。</p>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">送信</button>
</form>
{% endblock %}

kadai_002_2/NAGOYAEMESHI/userapp/templates/userapp/profile.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1>会員情報</h1>
    <table class="table">
        <tr>
            <th>氏名</th>
            <td>{{ user.username }}</td>
        </tr>
        <tr>
            <th>メールアドレス</th>
            <td>{{ user.email }}</td>
        </tr>
        <tr>
            <th>郵便番号</th>
            <td>{{ user.postal_code }}</td>
        </tr>
        <tr>
            <th>住所</th>
            <td>{{ user.address }}</td>
        </tr>
        <tr>
            <th>電話番号</th>
            <td>{{ user.phone_number }}</td>
        </tr>
        <tr>
            <th>誕生日</th>
            <td>{{ user.birthday }}</td>
        </tr>
        <tr>
            <th>職業</th>
            <td>{{ user.job }}</td>
        </tr>
    </table>
    <a href="{% url 'userapp:profile_edit' %}" class="btn btn-primary">編集</a>
</div>
{% endblock %}

kadai_002_2/NAGOYAEMESHI/userapp/templates/userapp/shop_info.html
<!-- shop_info.html -->
{% extends 'base.html' %}
{% load static %}

{% block css %}
<link rel="stylesheet" type="text/css" href="{% static 'css/review.css' %}">
{% endblock css %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title">{{ shop.name }}</h2>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-4">
            <!-- 店舗情報の表示 -->
        </div>
    </div>
    <br>
    <br>
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title">店舗基本情報</h2>
            <table class="table">
                <!-- 店舗の詳細情報 -->
            </table>
        </div>
    </div>

    <!-- メッセージの表示 -->
    <div class="row">
        <div class="col-md-12">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }}">
                        {{ message }}
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>

    <!-- 口コミ情報 -->
    <br>
    <div class="row">
        <div class="col-md-12">
            <h2 class="section-title">口コミ情報</h2>
            {% if review_list %}
                <h3>レビューコメント</h3>
                {% for item in review_list %}
                    <div class="balloon5">
                        <div class="faceicon">
                            <img src="{% static 'image/reviewer.png' %}">
                            <p class="small">{{ item.user }}</p>
                        </div>
                        <div class="chatting">
                            <div class="says">
                                <div class="star-rating">
                                    <div class="star-rating-front" style="width: {{ item.get_percent }}%">★★★★★</div>
                                    <div class="star-rating-back">★★★★★</div>
                                </div>
                                <br>
                                <p>{{ item.comment }}</p>
                                <p class="small">{{ item.created_at }}</p>            
                                {% if item.user == user %}
                                    <form method="post" action="{% url 'userapp:review_delete' item.pk %}">
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger">削除</button>
                                    </form>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% else %}
            <br>
                <p>まだレビューはありません。</p>
                <br>
            {% endif %}
            <hr>
            <h3>レビューを投稿する</h3>
            {% if user.is_authenticated %}
                <form class="login-form" action="" method="POST">
                    {{ review_form.non_field_errors }}
                    <div class="evaluation" style="float:left;">
                        <input id="score1" type="radio" name="score" value="5" />
                        <label for="score1"><span class="text">最高</span>★</label>
                        <input id="score2" type="radio" name="score" value="4" />
                        <label for="score2"><span class="text">良い</span>★</label>
                        <input id="score3" type="radio" name="score" value="3" />
                        <label for="score3"><span class="text">普通</span>★</label>
                        <input id="score4" type="radio" name="score" value="2" />
                        <label for="score4"><span class="text">悪い</span>★</label>
                        <input id="score5" type="radio" name="score" value="1" />
                        <label for="score5"><span class="text">最悪</span>★</label>
                    </div>
                    <br><br><br>
                    <label for="comment">コメント:</label>
                    <div class="form-group" type="text">{{ review_form.comment }}</div>
                    
                    {% csrf_token %}
                    <br>
                    <button type="submit" class="btn common-btn" name="review_submit">投稿する</button>
                    {% if form.errors %}
                    <br>
                    <p>エラー内容</p>
                        {% for field in form %}
                            {% for error in field.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        {% endfor %}
                    {% endif %} 
                </form>
            {% else %}
                <p>レビューコメントを残すにはログインが必要です。</p>
                <br>
                <a class="btn common-btn" href="{% url 'userapp:signup' %}">新規登録</a>
                <a class="btn common-btn-outline" href="{% url 'userapp:login' %}">ログイン</a>
            {% endif %}
        </div>
    </div>
    
    <!-- お気に入りボタン -->
    {% if user.is_authenticated %}
    {% if is_favorite %}
        <form method="post" action="{% url 'userapp:shop_info' shop_id=shop.id %}">
            {% csrf_token %}
            <button type="submit" name="unfavorite_submit" class="btn btn-danger">お気に入りから削除</button>
        </form>
    {% else %}
        <form method="post" action="{% url 'userapp:shop_info' shop_id=shop.id %}">
            {% csrf_token %}
            <button type="submit" name="favorite_submit" class="btn btn-primary">お気に入りに追加</button>
        </form>
    {% endif %}
    {% endif %}

    <!-- 予約フォーム -->
    <form method="post" action="{% url 'userapp:shop_info' shop_id=shop.id %}">
        {% csrf_token %}
        {{ reservation_form.as_p }}
        <button type="submit" name="reservation_submit" class="btn btn-success">予約する</button>
    </form>
</div>
{% endblock %}